CREATE TABLE clienti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ragione_sociale character varying(255) NOT NULL,
    active boolean,
    piva character varying(255),
    cf character varying(255),
    indirizzo character varying(255),
    civico character varying(255),
    cap integer,
    comune character varying(255),
    provincia character varying(255),
    telefono character varying(255),
    email character varying(255)
);

CREATE TABLE dispacciamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    costo_am Double precision NOT NULL,
    dis Double precision NOT NULL,
    capacita Double precision NOT NULL,
    sbilanciamento Double precision NOT NULL,
    mese integer NOT NULL,
    anno integer NOT NULL
);

CREATE TABLE fatture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_fattura character varying(255) NOT NULL,
    data_fattura date NOT NULL,
    cliente_id bigint NOT NULL,
    mese integer NOT NULL,
    anno integer NOT NULL,
    consumo_tot Double precision,
    consumo_tot_perdite Double precision,
    consumo_tot_reattivo Double precision,
    potenza_prelevata Double precision,
    totale_imponibile Double precision,
    totale_imposte Double precision,
    totale_iva Double precision,
    totale_materia Double precision,
    totale_oneri Double precision,
    totale_trasporto Double precision,
    pdf character varying(255),
    xlsx character varying(255)
);

CREATE TABLE fatture_forniture (
    fattura_id BIGINT NOT NULL,
    fornitura_pod character varying(255) NOT NULL
);

CREATE TABLE fatture_singole (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fattura_id bigint NOT NULL,
    fornitura_pod character varying(255) NOT NULL,
    dispacciamento_id bigint NOT NULL,
    oneri_id bigint NOT NULL,
    consumo_f1 Double precision,
    consumo_f1r Double precision,
    consumo_f2 Double precision,
    consumo_f2r Double precision,
    consumo_f3 Double precision,
    consumo_f3r Double precision,
    consumo_tot Double precision,
    consumo_tot_perdite Double precision,
    consumo_tot_reattivo Double precision,
    perditef1 Double precision,
    perditef2 Double precision,
    perditef3 Double precision,
    potenza_prelevata Double precision,
    totale_imponibile Double precision,
    totale_imposte Double precision,
    totale_iva Double precision,
    totale_materia Double precision,
    totale_oneri Double precision,
    totale_trasporto Double precision
);

CREATE TABLE forniture (
    pod character varying(255) NOT NULL PRIMARY KEY,
    cliente_id bigint NOT NULL,
    active boolean,
    indirizzo character varying(255),
    civico character varying(255),
    cap integer,
    comune character varying(255),
    provincia character varying(255),
    bta character varying(255) NOT NULL,
    potenza_disponibile Double precision NOT NULL,
    potenza_impegnata Double precision NOT NULL,
    tipo_prelievo character varying(255) NOT NULL,
    tipo_contatore character varying(255) NOT NULL,
    codice_distributore character varying(255) NOT NULL,
    fornitore character varying(255),
    fatturazione character varying(255) NOT NULL,
    iva Double precision NOT NULL,
    data_switch date NOT NULL,
    data_switch_out date,
    offerta_id bigint
);

CREATE SEQUENCE letture_id_seq
    START WITH 1
    INCREMENT BY 1
    CACHE 20;

CREATE TABLE letture (
    id BIGINT NOT NULL DEFAULT nextval('letture_id_seq') PRIMARY KEY,
    fornitura_pod character varying(255) NOT NULL,
    data_lettura date NOT NULL,
    is_utile boolean,
    validato character varying(255),
    tipo_dato character varying(255),
    tipo_lettura character varying(255) NOT NULL,
    causa_ostativa character varying(255),
    tipo_contatore character varying(255) NOT NULL,
    raccolta character varying(255),
    ea_f1 Double precision NOT NULL,
    ea_f2 Double precision NOT NULL,
    ea_f3 Double precision NOT NULL,
    er_f1 Double precision,
    er_f2 Double precision,
    er_f3 Double precision,
    pot_f1 Double precision,
    pot_f2 Double precision,
    pot_f3 Double precision,
    ka Double precision,
    kr Double precision,
    kp Double precision,
    pot_max character varying(255),
    note character varying(255)
);

CREATE TABLE letture_fatture_singole (
    lettura_id BIGINT,
    fattura_singola_id BIGINT,
    tipo character varying(255)
);

CREATE TABLE offerte (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome character varying(255) NOT NULL,
    codice character varying(255),
    tipo character varying(255),
    ocv Double precision,
    ocf Double precision,
    is_c_mag boolean,
    maggiorazione Double precision,
    is_pun boolean,
    f1 Double precision,
    f2 Double precision,
    f3 Double precision,
    has_spread boolean,
    spread Double precision,
    data_inizio date,
    data_fine date,
    descrizione character varying(255)
);

CREATE TABLE oneri (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo character varying(255) NOT NULL,
    qe_tud Double precision NOT NULL,
    qp_tdm Double precision NOT NULL,
    qf_tud Double precision NOT NULL,
    qf_mis Double precision NOT NULL,
    qe_arim Double precision NOT NULL,
    qe_asos Double precision NOT NULL,
    qe_uc3 Double precision NOT NULL,
    qe_uc6 Double precision NOT NULL,
    qp_arim Double precision NOT NULL,
    qp_asos Double precision NOT NULL,
    qf_arim Double precision NOT NULL,
    qf_asos Double precision NOT NULL,
    qf_uc6 Double precision NOT NULL,
    qf_dbt Double precision NOT NULL,
    trasmissione Double precision NOT NULL,
    accise Double precision NOT NULL,
    trimestre integer NOT NULL,
    anno integer NOT NULL
);

CREATE TABLE pun (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mese integer NOT NULL,
    anno integer NOT NULL,
    f1 Double precision NOT NULL,
    f2 Double precision NOT NULL,
    f3 Double precision NOT NULL,
    fornitura_pod character varying(255) NOT NULL
);

CREATE TABLE pun_pod (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mese integer NOT NULL,
    anno integer NOT NULL,
    f1 Double precision NOT NULL,
    f2 Double precision NOT NULL,
    f3 Double precision NOT NULL,
    fornitura_pod character varying(255) NOT NULL
);

CREATE TABLE cmor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornitura_pod character varying(255) NOT NULL,
    importo Double precision NOT NULL,
    mese integer NOT NULL,
    anno integer NOT NULL
);

CREATE TABLE ruoli (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruolo character varying(255)
);

CREATE TABLE ruoli_utenti (
    ruolo_id bigint NOT NULL,
    utente_id bigint NOT NULL
);

CREATE TABLE utenti (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(255),
    password character varying(255),
    nome character varying(255),
    cognome character varying(255),
    email character varying(255),
    created_at timestamp(6) without time zone,
    url_avatar character varying(255)
);

--

ALTER TABLE fatture_singole
    ADD CONSTRAINT fk_fatture_singole_fatture_id FOREIGN KEY (fattura_id) REFERENCES fatture(id);

-- ALTER TABLE fatture_singole
--     ADD CONSTRAINT fk_fatture_singole_oneri_id FOREIGN KEY (oneri_id) REFERENCES oneri(id);

-- ALTER TABLE  fatture_singole
--     ADD CONSTRAINT fk_fatture_singole_fornitura_pod FOREIGN KEY (fornitura_pod) REFERENCES forniture(pod);

-- ALTER TABLE  fatture_singole
--     ADD CONSTRAINT fk_fatture_singole dispacciamento_id FOREIGN KEY (dispacciamento_id) REFERENCES dispacciamento(id);


ALTER TABLE pun
    ADD CONSTRAINT fk_pun_forniture_pod FOREIGN KEY (fornitura_pod) REFERENCES forniture(pod);

ALTER TABLE pun_pod
    ADD CONSTRAINT fk_pun_pod_forniture_pod FOREIGN KEY (fornitura_pod) REFERENCES forniture(pod);

ALTER TABLE cmor
    ADD CONSTRAINT fk_cmor_forniture_pod FOREIGN KEY (fornitura_pod) REFERENCES forniture(pod);

ALTER TABLE  ruoli_utenti
    ADD CONSTRAINT fk_ruoli_utenti_utenti_id FOREIGN KEY (utente_id) REFERENCES utenti(id);

ALTER TABLE  ruoli_utenti
    ADD CONSTRAINT fk_ruoli_utenti_ruoli_id FOREIGN KEY (ruolo_id) REFERENCES ruoli(id);

ALTER TABLE  letture
    ADD CONSTRAINT fk_letture_forniture_pod FOREIGN KEY (fornitura_pod) REFERENCES forniture(pod) ON DELETE CASCADE;

ALTER TABLE  fatture
    ADD CONSTRAINT fk_fatture_clienti_id FOREIGN KEY (cliente_id) REFERENCES clienti(id);

ALTER TABLE  forniture
    ADD CONSTRAINT fk_forniture_cliente_id FOREIGN KEY (cliente_id) REFERENCES clienti(id) ON DELETE CASCADE;

ALTER TABLE  forniture
    ADD CONSTRAINT fk_forniture_offerte_id FOREIGN KEY (offerta_id) REFERENCES offerte(id);


ALTER TABLE  fatture_forniture
    ADD CONSTRAINT fk_fatture_forniture_fatture_id FOREIGN KEY (fattura_id) REFERENCES fatture(id);


ALTER TABLE  fatture_forniture
    ADD CONSTRAINT fk_fatture_forniture_forniture_pod FOREIGN KEY (fornitura_pod) REFERENCES forniture(pod);


ALTER TABLE  letture_fatture_singole
    ADD CONSTRAINT fk_letture_fatture_singole_fatture_singole_id FOREIGN KEY (fattura_singola_id) REFERENCES fatture_singole(id);



